# Mars Rover Mission Configuration
# Customize your mission parameters here!

grid:
  width: 10
  height: 10
  obstacles:
    - [2, 2]
    - [3, 5]
    - [7, 8]

rover:
  start_x: 0
  start_y: 0
  start_direction: "N"  # N, S, E, W

mission:
  name: "Mars Exploration Mission Alpha"
  enable_telemetry: true
  telemetry_folder: "telemetry"
